project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

author: "JADA"

website:
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.pdf
      - icon: file-play-fill
        href: https://www.youtube.com/watch?v=T6lBfRbZmXk&feature=youtu.be
      - text: Proposal
        href: proposal.qmd
      - text: About
        href: about.qmd
      - text: Contract
        href: contract.qmd
    right:
      - icon: github
        href: https://github.com/sta199-f24/project-jada

format:
  html:
    theme: default
