project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

author: "Allison Yang, Ashley Deleon, Daniel Matten, Jacob Ominsky"

website:
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.pdf
      - text: Proposal
        href: proposal.qmd
      - text: About
        href: about.qmd
      - text: Contract
        href: contract.qmd

format:
  html:
    theme: default
