---
title: Influence of National Resources on Country Conflict
subtitle: Report
execute:
  echo: true
---

This study examines the relationship between a country's national material capabilities—such as military expenditures, personnel, and iron—and its frequency engaging in conflict. By analyzing data from the Correlates of War project, which tracks national capabilities and militarized interstate disputes, the research aims to identify whether increases in these capabilities correlate with higher frequencies of interstate conflict. The findings seek to enhance our understanding of how shifts in state power influence international stability and conflict dynamics.


## Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won’t fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

Motivation:

The primary motivation for this research is to explore the relationship between national material capabilities and a country’s likelihood of being involved in conflicts. Understanding how changes in a nation’s military capabilities—such as military expenditures and natural resources like iron—affect its involvement in international disputes is important for assessing political stability. This research aligns with the broader theme of examining how data can explain political dynamics, provide insights into state behavior, and potentially help predict future conflicts. In analyzing the intersection of politics and data, this study aims to tell a story about how power, in its different forms, shapes international relations. 

Source:

The data used in this analysis comes from the Correlates of War (COW) project, which is widely used by Political Scientists. This project involves two datasets for our research:

National Material Capabilities (Dataset 1)
This dataset includes data on military power indicators such as military expenditures, military personnel, energy consumption, and total population for various countries. The data is collected annually, providing a comprehensive look at the material capabilities of each nation over time.

Militarized Interstate Disputes (Dataset 2)
This dataset records instances where states threaten, display, or use force against one another. The data includes details such as the start and end dates of conflicts, number of combatants, casualties, and the outcomes of these disputes. This dataset spans from 1816 to 2014 and provides insight into the frequency and intensity of conflicts between countries.

## Methodology

This section includes a brief description of your analysis process.
Explain the reasoning for the types of analyses you do, exploratory, inferential, or modeling.
If you’ve chosen to do inference, make sure to include a justification for why that inferential approach is appropriate.
If you’ve chosen to do modeling, describe the model(s) you’re fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, interactions considered, variable transformations (if needed), assessment of conditions and diagnostics, and any other relevant considerations that were part of the model fitting process.

## Results

This is where you will discuss your overall finding and describe the key results from your analysis.
The goal is not to interpret every single element of an output shown, but instead to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.

## Discussion

In this section you’ll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, this section will include ideas for future work.

